# This is a basic workflow to help you get started with Actions

name: Deploy React App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Get code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: react-project/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('react-project/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      # Runs a single command using the runners shell
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: cd react-project && npm install

      - name: Run tests
        run: cd react-project && npm test

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      js-file: ${{ steps.publish.outputs.js-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: cd react-project && npm install
      - name: Build
        run: cd react-project && npm run build
      - name: Publish js filename
        id: publish
        run: find react-project/dist/assets/*.js -type f -execdir echo '::set-output name=js-file::{}' ';'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: react-project/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Output contents
        run: ls -la
      - name: Get js file
        run: echo "${{ needs.build.outputs.js-file }}"
      - name: Deploy
        run: echo "Deploying to GitHub Pages"
